default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: website_development

test:
  <<: *default
  database: website_test

production:
  <<: *default
  database: website_production
  username: tristinbaker
  password: <%= ENV['WEBSITE_DATABASE_PASSWORD'] %>
